### ISSUE TITLE
presentations/reveal.js/{css,js,lib,plugin} Fails

### ISSUE THREAD

**Issue by nbulischeck** [CUCyber/presentations#1]
presentations/reveal.js/{css,js,lib,plugin}" failed: No such file or directory (2)

I thought that was supposed to work, but apparently it doesn't like that. 

The expanded version works just fine.

	rsync -av --delete reveal.js/css "$(OUTDIR)$(ROOT)"reveal
	rsync -av --delete reveal.js/js "$(OUTDIR)$(ROOT)"reveal
	rsync -av --delete reveal.js/lib "$(OUTDIR)$(ROOT)"reveal
	rsync -av --delete reveal.js/plugin "$(OUTDIR)$(ROOT)"reveal

**Comment by lilyinstarlight** [comment]
Is this a fresh clone? When I updated reveal.js, existing clones got broken.

**Comment by nbulischeck** [comment]
Fresh clone as of 2 days ago

**Comment by lilyinstarlight** [comment]
Fixed in 1cb7025.
